config/routes.rb
Rails.application.routes.draw do
  resources :resumes, only: [:index, :show, :new, :create, :destroy]   
  root "resumes#index"  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
	validates :name, presence: true # Make sure the owner's name is present.   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
  	@resumes = Resume.all   
  end

  def new
  	@resume = Resume.new   
  end

  def show_image
  	@resume = Resume.find(params[:id])
  	send_data @resume.image, :type => 'image/png',:disposition => 'inline'
  end

  def show
  	@resume = Resume.find(params[:id])
  end  

  def create
  	@resume = Resume.new(resume_params)   
         
    if @resume.save   
        redirect_to resumes_path, notice: "Successfully uploaded."   
    else   
        render "new"   
    end   
  end

  def destroy
  	@resume = Resume.find(params[:id])   
    @resume.destroy   
    redirect_to resumes_path, notice:  "Successfully deleted."   
  end

  private   
    def resume_params   
    	params.require(:resume).permit(:name, :attachment)   
  	end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>File Upload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/resumes/create.html.erb
<h1>Resume#create</h1>
<p>Find me in app/views/resume/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resume#destroy</h1>
<p>Find me in app/views/resume/destroy.html.erb</p>

app/views/resumes/index.html.erb
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  
<%= link_to "New Resume", new_resume_path %>   
<br>   
<br>   
  
<table border="3">   
   <thead>   
      <tr>   
         <th>Candidate Name</th>   
         <th>Download Link</th>   
         <th>Action</th>   
      </tr>   
   </thead>   
      
   <tbody>   
      <% @resumes.each do |resume| %>   
            
         <tr>   
            <td><%= resume.name %></td>   
            <td><%= image_tag url_for(resume.attachment_url), :class => "img-fluid", style: "width:350px; padding: 10px;" %></td>
    		<td><%= link_to 'Show', resume_path(resume) %></td> 
            <td><%= link_to "Delete",  resume, method: :delete, confirm: "Are you sure you want to delete #{resume.name}?" %></td>   
         </tr>   
            
      <% end %>   
   </tbody>   
      
</table>   
</div>  

app/views/resumes/new.html.erb
<div class="container">   
<% if !@resume.errors.empty? %>   
   <div>   
         
      <ul>   
         <% @resume.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
         <% end %>   
<div class="container">   
	<% if !@resume.errors.empty? %>   
	   <div>   
	         
	      <ul>   
	         <% @resume.errors.full_messages.each do |msg| %>   
	            <li><%= msg %></li>   
	         <% end %>      </ul>   
	         
	   </div>   
	<% end %>
<% end %>   
	  
	<div>   
	   <%= form_for @resume, html: { multipart: true } do |f| %>   
	      <%= f.label :name %>   
	      <%= f.text_field :name %>   
	      <br><br>   
	      <%= f.label :attachment %>   
	      <%= f.file_field :attachment %>   
	      <br>   
	      <%= f.submit "Save" %>   
	   <% end %>   
	</div>   
</div>  

app/views/resumes/show.html.erb
<div class="container">
	<p>
	  <strong>Judul:</strong>
	  <%= @resume.name %>
	</p>

	<p>
	  <strong>Title:</strong>
	  <img src="<%= @resume.attachment %>" class="img-fluid" style="width: 50%;" alt="">
	  
	</p>
	<%= link_to 'Back', resumes_path %>
</div>